version: '3.9'
services:
  php:
    image: php_todo_app
    working_dir: /home/user/app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: /bin/sh
    tty: true
    stdin_open: true
    stop_signal: SIGKILL
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: password123456
    volumes:
      - ./:/home/user/app
    ports:
      - '${PORT:-8000}:${PORT:-8000}'
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: password123456
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password123456
    volumes:
      - mysqldata:/var/lib/mysql
  myadmin:
    image: phpmyadmin/phpmyadmin:5.2
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password123456
    depends_on:
      - db
    ports:
      - ${MY_ADMIN_PORT:-8081}:80
volumes:
  mysqldata: